// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW99Z6_oeNMnMF6x322sNMWrdJs9MaFT8',
    appId: '1:233797822107:android:8c6ba77cc78275a9cd083e',
    messagingSenderId: '233797822107',
    projectId: 'olabisiolai-flutter-app',
    databaseURL: 'https://olabisiolai-flutter-app-default-rtdb.firebaseio.com',
    storageBucket: 'olabisiolai-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJ8jELBtgdahpYfh_4I8dc2HV1n5e3SM',
    appId: '1:233797822107:ios:8e99f68a6c20d713cd083e',
    messagingSenderId: '233797822107',
    projectId: 'olabisiolai-flutter-app',
    databaseURL: 'https://olabisiolai-flutter-app-default-rtdb.firebaseio.com',
    storageBucket: 'olabisiolai-flutter-app.firebasestorage.app',
    androidClientId: '233797822107-mdvmmrg6hl45lgqhimr9or66n85vrbln.apps.googleusercontent.com',
    iosClientId: '233797822107-v426oj9rnpfoj9jsiiqi39hlsv315jhr.apps.googleusercontent.com',
    iosBundleId: 'com.olabisiolai.gidira',
  );

}