// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp6VEjvqGNEvBBe_sm8rEYLEFoK38fOJk',
    appId: '1:953237213749:web:13dddb9e154013edee577c',
    messagingSenderId: '953237213749',
    projectId: 'batteryqk-webapp',
    authDomain: 'batteryqk-webapp.firebaseapp.com',
    storageBucket: 'batteryqk-webapp.firebasestorage.app',
    measurementId: 'G-CFC0HKJ1S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMX-2-OV4pT6sCd6nqePO4d9rjb8yOtUI',
    appId: '1:953237213749:android:8ed11de6f625abb3ee577c',
    messagingSenderId: '953237213749',
    projectId: 'batteryqk-webapp',
    storageBucket: 'batteryqk-webapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByoVPeA6KWO40EDRPpKmwf75bMObMJOJE',
    appId: '1:953237213749:ios:33f822375d992e16ee577c',
    messagingSenderId: '953237213749',
    projectId: 'batteryqk-webapp',
    storageBucket: 'batteryqk-webapp.firebasestorage.app',
    iosBundleId: 'com.example.batteryqkWebApp',
  );
}
